config/routes.rb
Rails.application.routes.draw do
  root to: 'productos#index'
  devise_for :usuarios
  get 'productos', to: 'productos#index'
  get 'productos/new', as: 'new_producto'
  get 'productos/:id/edit', to: 'productos#edit', as: 'edit_producto'
  post 'productos/create', to: 'productos#create', as: 'create_producto'
  patch 'productos/update', to: 'productos#update', as: 'update_producto'
  delete 'productos/:id/destroy', to: 'productos#destroy', as: 'destroy_producto'
  resources :rubros
  resources :marcas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
    validates :nombre, uniqueness: true
end

app/models/producto.rb
class Producto < ApplicationRecord
    belongs_to :marca
    belongs_to :rubro
end

app/models/rubro.rb
class Rubro < ApplicationRecord
    validates :nombre, uniqueness: true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index]

  # GET /marcas
  # GET /marcas.json
  def index
    @marcas = Marca.all
  end

  # GET /marcas/1
  # GET /marcas/1.json
  def show
  end

  # GET /marcas/new
  def new
    @marca = Marca.new
  end

  # GET /marcas/1/edit
  def edit
  end

  # POST /marcas
  # POST /marcas.json
  def create
    @marca = Marca.new(marca_params)

    respond_to do |format|
      if @marca.save
        format.html { redirect_to marcas_path, notice: 'Marca creada.' }
        format.json { render :show, status: :created, location: @marca }
      else
        format.html { render :new }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marcas/1
  # PATCH/PUT /marcas/1.json
  def update
    respond_to do |format|
      if @marca.update(marca_params)
        format.html { redirect_to marcas_path, notice: 'Marca actualizada.' }
        format.json { render :show, status: :ok, location: @marca }
      else
        format.html { render :edit }
        format.json { render json: @marca.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marcas/1
  # DELETE /marcas/1.json
  def destroy
    begin
    @marca.destroy
    respond_to do |format|
      format.html { redirect_to marcas_url, notice: 'Marca eliminada.' }
      format.json { head :no_content }
    end
  rescue Exception
    redirect_to marcas_url
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marca
      @marca = Marca.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def marca_params
      params.require(:marca).permit(:nombre)
    end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController

  before_action :set_marcas_rubros, only: [:edit, :new]
  before_action :set_producto, only: [:edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index]

  def index
    @productos = Producto.all
  end

  def new
    @producto = Producto.new
  end

  def edit
  end

  def create
    @producto = Producto.new(producto_params)
    if @producto.save
      redirect_to productos_url
    else
      render :new
    end
  end

  def update
    if @producto.update(producto_params)
      redirect_to productos_url
    else
      render :edit
    end
  end

  def destroy
     @producto.destroy
      redirect_to productos_url
  end

  private
    # Agrega listado para select 
    def set_marcas_rubros
      @marcas = Marca.all
      @rubros = Rubro.all
    end

    # Busca producto según id pasado por parámetros
    def set_producto
      @producto = Producto.find(params['id'] || params['producto']['id'])
    end

    # Parámetros pasados por formulario
    def producto_params
      params.require(:producto).permit(:nombre, :cantidad_minima, :cantidad_actual, :precio, :marca_id, :rubro_id, :activo)
    end
end

app/controllers/rubros_controller.rb
class RubrosController < ApplicationController
  before_action :set_rubro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_usuario!, except: [:index]

  # GET /rubros
  # GET /rubros.json
  def index
    @rubros = Rubro.all
  end

  # GET /rubros/1
  # GET /rubros/1.json
  def show
  end

  # GET /rubros/new
  def new
    @rubro = Rubro.new
  end

  # GET /rubros/1/edit
  def edit
  end

  # POST /rubros
  # POST /rubros.json
  def create
    @rubro = Rubro.new(rubro_params)

    respond_to do |format|
      if @rubro.save
        format.html { redirect_to rubros_path, notice: 'Rubro creado.' }
        format.json { render :show, status: :created, location: @rubro }
      else
        format.html { render :new }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rubros/1
  # PATCH/PUT /rubros/1.json
  def update
    respond_to do |format|
      if @rubro.update(rubro_params)
        format.html { redirect_to rubros_path, notice: 'Rubro actualizado.' }
        format.json { render :show, status: :ok, location: @rubro }
      else
        format.html { render :edit }
        format.json { render json: @rubro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rubros/1
  # DELETE /rubros/1.json
  def destroy
    begin
    @rubro.destroy 
    respond_to do |format|
      format.html { redirect_to rubros_url, notice: 'Rubro eliminado.' }
      format.json { head :no_content }
    end
    rescue Exception
      redirect_to rubros_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rubro
      @rubro = Rubro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rubro_params
      params.require(:rubro).permit(:nombre, :perecedero)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/rubros_helper.rb
module RubrosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final - DW3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      a:hover{
        background-color: #007bff;
      }
    </style>
  </head>

  <body class="m-0">
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-dark bg-primary">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                      <li class="ml-3 text-white"><%= link_to "Productos", productos_path, :class => "text-white" %></li>
                      <li class="ml-3 text-white"><%= link_to "Marcas", marcas_path, :class => "text-white" %></li>
                      <li class="ml-3"><%= link_to "Rubros", rubros_path, :class => "text-white" %></li>
                    </ul>
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                       <% if usuario_signed_in? %>
                       <li>
                            <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle text-white" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <%= current_usuario.email %>
                            </a>
                                <div class="dropdown-menu dropdown-menu-right bg-info text-white" aria-labelledby="navbarDropdown">
                                    <%= link_to "Cerrar sesión", destroy_usuario_session_path, method: :delete, :class => "dropdown-item bg-info text-white" %> </li>
                                </div>
                            </li>
                          </li>
                        <% else %>
                        <li>
                          <%= link_to "Iniciar sesión", new_usuario_session_path, :class => "text-white" %> </li>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <% flash.each do |type, msg| %>
          <div>
            <%= msg %>
          </div>
        <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/marcas/_form.html.erb
<%= form_with(model: marca, local: true) do |form| %>
  <% if marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
        <% marca.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre, :class => "form-label" %>
    <%= form.text_field :nombre, :class => "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<div class="container p-5">
    <h1>Editar Marca</h1>

    <%= render 'form', marca: @marca %>

    <%= link_to 'Volver al listado', marcas_path %>
</div>

app/views/marcas/index.html.erb
<div class="container p-5">

<p id="notice"><%= notice %></p>

<h1>Marcas</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.nombre %></td>
        <td><%= link_to 'Editar', edit_marca_path(marca) %></td>
        <td><%= link_to 'Eliminar', marca, method: :delete, data: { confirm: 'Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Marca', new_marca_path %>
</div>

app/views/marcas/new.html.erb
<div class="container p-5">

    <h1>Nueva Marca</h1>

    <%= render 'form', marca: @marca %>

    <%= link_to 'Volver al listado', marcas_path %>
</div>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @marca.nombre %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>

app/views/productos/_form.html.erb
<%= form_with(model: producto, local: true, url: ruta) do |form| %>

  <%= form.hidden_field :id %>

  <div class="field">
    <%= form.label :marca_id, "Marca" %>
    <%= form.collection_select :marca_id, @marcas, :id, :nombre, {}, { :class => 'form-control' } %>
  </div>

  <div class="field">
   <%= form.label :rubro_id, "Rubro" %>
    <%= form.collection_select :rubro_id, @rubros, :id, :nombre, {}, { :class => 'form-control' } %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cantidad_minima %>
    <%= form.number_field :cantidad_minima, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :cantidad_actual %>
    <%= form.number_field :cantidad_actual, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, step: 0.01, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :activo %>
    <%= form.check_box :activo %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<div class="container">

<h1>Editar Producto</h1>

<%= render 'form', producto: @producto, ruta: update_producto_path %>

<%= link_to 'Volver al listado', productos_path %>
</div>

app/views/productos/index.html.erb
<div class="container p-5">

<h1>Productos</h1>

<table class="table text-center">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cantidad Mínima</th>
      <th>Cantidad Actual</th>
      <th>Precio</th>
      <th>Marca</th>
      <th>Rubro</th>
      <th>Activo</th>
      <th colspan="2"><%= link_to 'Nuevo producto', new_producto_path, :class=>"btn btn-info text-white" %></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.nombre %></td>
        <td><%= producto.cantidad_minima %></td>
        <td><%= producto.cantidad_actual %></td>
        <td><%= producto.precio %></td>
        <td><%= producto.marca.nombre %></td>
        <td><%= producto.rubro.nombre %></td>
        <td class="text-light <%= producto.activo ? "bg-success" : "bg-danger" %>"><%= producto.activo ? "SI" : "NO" %></td>
        <td><%= link_to 'Editar', edit_producto_path(producto) %></td>
        <td><%= link_to 'Eliminar', destroy_producto_path(producto), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/productos/new.html.erb
<div class="container">

    <h1>Nuevo Producto</h1>

    <%= render 'form', producto: @producto, ruta: create_producto_url %>

    <%= link_to 'Volver al listado', productos_path %>

</div>

app/views/rubros/_form.html.erb
<%= form_with(model: rubro, local: true) do |form| %>
  <% if rubro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rubro.errors.count, "error") %> prohibited this rubro from being saved:</h2>

      <ul>
        <% rubro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, :class => "form-control" %>
  </div>

  <div class="field">
    <%= form.label :perecedero %>
    <%= form.check_box :perecedero %>
  </div>

  <div class="actions">
    <%= form.submit 'Guardar', :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/rubros/edit.html.erb
<div class="container p-5">

    <h1>Editar Rubro</h1>

    <%= render 'form', rubro: @rubro %>

    <%= link_to 'Volver al listado', rubros_path %>

</div>

app/views/rubros/index.html.erb
<div class="container p-5">
  <p id="notice"><%= notice %></p>

  <h1>Rubros</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Perecedero</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @rubros.each do |rubro| %>
        <tr>
          <td><%= rubro.nombre %></td>
          <td class="text-light <%= rubro.perecedero ? "bg-danger" : "bg-success" %>"><%= rubro.perecedero ? "SI" : "NO" %></td>
          <td><%= link_to 'Editar', edit_rubro_path(rubro) %></td>
          <td><%= link_to 'Eliminar', rubro, method: :delete, data: { confirm: 'Estás segura de ello?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nuevo Rubro', new_rubro_path %>
</div>

app/views/rubros/new.html.erb
<div class="container p-5">

    <h1>Nuevo Rubro</h1>

    <%= render 'form', rubro: @rubro %>

    <%= link_to 'Volver al listado', rubros_path %>
    
</div>

app/views/rubros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @rubro.nombre %>
</p>

<p>
  <strong>Perecedero:</strong>
  <%= @rubro.perecedero %>
</p>

<%= link_to 'Edit', edit_rubro_path(@rubro) %> |
<%= link_to 'Back', rubros_path %>